namespace VisiFlow.Data.Entities;

/// <summary>Table VisitPlanEntries. One planned/prioritized visit for a customer in a given month -
/// generated by the visit-planning algorithm. Regenerating a (company, year, month) plan replaces all
/// its entries.</summary>
public class VisitPlanEntry
{
    public int Id { get; set; }
    public int CompanyId { get; set; }
    public Company Company { get; set; } = null!;
    public int PlanYear { get; set; }
    /// <summary>1-12</summary>
    public int PlanMonth { get; set; }
    public string CustomerNumber { get; set; } = null!;
    /// <summary>התאריך המתוכנן לביקור. Null אם לא ניתן היה לשבץ את הלקוח בקיבולת הזמינה החודש.</summary>
    public DateTime? PlannedDate { get; set; }
    public string? AgentName { get; set; }
    /// <summary>ציון עדיפות סופי (0-100), אחרי שקלול המשקלים.</summary>
    public decimal PriorityScore { get; set; }
    /// <summary>ציוני הרכיבים המנורמלים (0-1 כל אחד) - לשקיפות/הצגה למשתמש.</summary>
    public decimal SalesDropScore { get; set; }
    public decimal DistributionScore { get; set; }
    public decimal FrequencyScore { get; set; }
    public decimal VisitStandardScore { get; set; }
    public decimal DaysSinceVisitScore { get; set; }
    /// <summary>ימים שעברו מאז הביקור האחרון בפועל, נכון למועד יצירת התוכנית - null אם הלקוח מעולם לא בוצע אצלו ביקור.
    /// נשמר בנפרד מהציון המנורמל כדי להציג את הערך הגולמי למשתמש.</summary>
    public int? DaysSinceLastVisit { get; set; }
    public DateTime GeneratedAt { get; set; }
    /// <summary>מתי בוצעה התערבות ידנית אחרונה בתאריך של השורה הזו (על ידי מנהל במסך תוכנית הביקורים,
    /// או על ידי הסוכן שדחה ביקור מממשק הסוכן) - null אם השורה עדיין כפי שהאלגוריתם קבע אותה.</summary>
    public DateTime? ManuallyModifiedAt { get; set; }
    /// <summary>תיאור קריא של ההתערבות הידנית האחרונה, למשל "הוזז ידנית על ידי מנהל מ-02/09 ל-05/09"
    /// או "הוזז על ידי הסוכן (לא ביקר - סיבה: ...) מ-02/09 ל-03/09".</summary>
    public string? ManuallyModifiedNote { get; set; }
    /// <summary>מתי הוזזה השורה לאחרונה על ידי כפתור "אופטימיזציה לפי עיר" - null אם מעולם לא. נפרד
    /// מ-ManuallyModifiedAt בכוונה: זו הזזה אוטומטית של המערכת, לא התערבות אנושית, ולכן לא נכללת
    /// בהחרגה של האופטימיזציה מהזזת שורות (ריצה חוזרת עדיין רשאית לזוז שורות שהיא עצמה כבר הזיזה).</summary>
    public DateTime? CityOptimizedAt { get; set; }
    /// <summary>תיאור קריא של הריכוז לפי עיר האחרון על השורה, למשל "רוכז לפי עיר (תל אביב) מ-04/09 ל-02/09".</summary>
    public string? CityOptimizedNote { get; set; }
    /// <summary>הערה חופשית שהמנהל מוסיף לשורה הזו במסך "תוכנית הביקורים" - מוצגת לסוכן בממשק שלו על
    /// כרטיס הלקוח, כדי להעביר מסר או דגש מיוחד לקראת הפגישה הספציפית הזו (למשל "לבדוק מלאי לפני
    /// שמגיעים" או "הלקוח ביקש להתקשר לפני הביקור"). שונה מ-ManuallyModifiedNote/CityOptimizedNote -
    /// אלה תיעוד אוטומטי של המערכת על מה שקרה לשורה, וזו הודעה אנושית מכוונת מהמנהל לסוכן.</summary>
    public string? AdminNote { get; set; }
}
